Transform: AWS::Serverless-2016-10-31
Parameters:
  EventBusName:
    Type: String
    Default: StripeEventBus
    Description: (Required) Name of EventBus.
  StripeWebhookSecret:
    Type: String
    Default: wshec_1234
    Description: (Required) Your Stripe webhooks secret
  StripeSecretKey:
    Type: String
    Default: sk_12345
    Description: (Required) Your Stripe secret key
Resources:
  EventReciever:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: send-to-event-bus.handler
      CodeUri: s3://stripe-event-bus/6a9736d71e71dc6010da4c9c33824f2c
      Environment:
        Variables:
          EVENT_BUS_NAME:
            Ref: EventBusName
          STRIPE_WEBHOOK_SECRET:
            Ref: StripeWebhookSecret
          STRIPE_SECRET_KEY:
            Ref: StripeSecretKey
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - events:PutEvents
          Resource: '*'
      Events:
        WebhookEndpoint:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: StripeEventBus
  EventProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: event-processor.handler
      CodeUri: s3://stripe-event-bus/6a9736d71e71dc6010da4c9c33824f2c
  EventListener:
    Type: AWS::Events::Rule
    Properties:
      Description: Handles Stripe events
      EventBusName:
        Fn::GetAtt:
        - EventBus
        - Name
      EventPattern:
        source:
        - Stripe
        detail-type:
        - payment_intent.succeeded
      Targets:
      - Id: something
        Arn:
          Fn::GetAtt:
          - EventProcessor
          - Arn
  EventProcessorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - EventProcessor
        - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - EventListener
        - Arn
